"""MimCore constants - re-export from hermes_constants."""

from mimir_constants import (
    get_hermes_home,
    get_default_hermes_root,
    get_config_path,
    get_env_path,
    get_skills_dir,
    get_optional_skills_dir,
    get_subprocess_home,
    get_hermes_dir,
    display_hermes_home,
    apply_ipv4_preference,
    parse_reasoning_effort,
    is_termux,
    is_wsl,
    is_container,
    VALID_REASONING_EFFORTS,
    OPENROUTER_BASE_URL,
    OPENROUTER_MODELS_URL,
    AI_GATEWAY_BASE_URL,
)

__all__ = [
    "get_hermes_home",
    "get_default_hermes_root", 
    "get_config_path",
    "get_env_path",
    "get_skills_dir",
    "get_optional_skills_dir",
    "get_subprocess_home",
    "get_hermes_dir",
    "display_hermes_home",
    "apply_ipv4_preference",
    "parse_reasoning_effort",
    "is_termux",
    "is_wsl",
    "is_container",
    "VALID_REASONING_EFFORTS",
    "OPENROUTER_BASE_URL",
    "OPENROUTER_MODELS_URL",
    "AI_GATEWAY_BASE_URL",
]
